### ISSUE TITLE
[T1.P1]: Es válido repetir un a^i

### ISSUE THREAD

**Issue by fdominguezclaro** [PUC-IIC2223/syllabus#10]
Hola! 

Para el lenguaje de la P1, es válida la siguiente palabra? 

```
#a#aa#a#aa
```

En palabras, se puede repetir el `a^i`?

**Comment by Drpinto1** [comment]
¡Hola!

La palabra que escribes es válida, es posible repetir los `a^i`.

La única restricción sobre el número de `a^i` (que en el enunciado se define como `k`) es que sea mayor o igual a 1

Edit: Con lo anterior me refiero al número de "grupos de letras `a`"; si hablamos de la cantidad de letras `a` por cada grupo, cantidad a la que nos referimos como `i` (o `i_j` para el caso más general), está además tiene la restricción de ser menor o igual a `n`.

¡Saludos!

**Comment by fdominguezclaro** [comment]
Perfecto. Gracias!!
