### ISSUE TITLE
[T1.P1.1&T1.P2.2] Duda uso DFAp

### ISSUE THREAD

**Issue by StroveLight** [PUC-IIC2223/syllabus#12]
Hola,
Para la P1.1 se puede usar DFAp?

Para la P2.2, se considera DFAp?

**Comment by Drpinto1** [comment]
¡Hola @StroveLight!

La idea para ambas preguntas es que usen/consideren solamente los DFA tradicionales.

Dicho esto, si se te ocurre un DFAp para la pregunta 1 no debería ser demasiado complejo construir un DFA a partir de este.

¡Saludos!
