### ISSUE TITLE
[T1.P1.2] Cantidad de estados

### ISSUE THREAD

**Issue by smrebolledo** [PUC-IIC2223/syllabus#13]
Cuando dicen que debe tener n+1 estados significa estados desde 0 hasta n o desde 0 hasta n+1?

**Comment by fgbruna** [comment]
Hola @smrebolledo! , se refiere a que la cardinalidad del conjunto de estados debe ser n + 1. Piensa que de 0 a n+1 habrían n + 2 estados.
