### ISSUE TITLE
[Administrativo]

### ISSUE THREAD

**Issue by VicenteMerino** [PUC-IIC2223/syllabus#14]
![image](https://user-images.githubusercontent.com/47841749/91099038-93c1ed00-e630-11ea-8108-353180c54db4.png)

Hola, no me aparece la opción de descargar las clases, no se si saben como solucionarlo?

**Comment by crivero1** [comment]
Hola Vicente, 

Con tu mensaje nos acabo de dar cuenta que al acceder la grabación no tienes habilitado el link para bajar el video (en mi cuenta si aparece). Vamos a revisar cómo habilitar esto y te respondemos dentro de poco. 

Saludos!

**Comment by crivero1** [comment]
Hola Vicente,

Acabo de actualizar los links de las grabaciones y ahora si esta habilitado para descargar los videos. Por favor pruebalo y cuentame si esta funcionando bien. 

De hecho, creo haber habilitado que los videos NO se borrarán durante todo el semestre. Ahora bien, desde la Universidad me insistieron tanto que se van a borrar en 14 días que les recomiendo respaldarlos si piensan que los necesitarán a futuro. 

Suerte!

**Comment by VicenteMerino** [comment]
Ahora si está funcionando. Gracias profe!

**Comment by crivero1** [comment]
Excelente. Saludos!
