### ISSUE TITLE
[T1.P1] Duda restricciones de la palabra w

### ISSUE THREAD

**Issue by CristobalHV** [PUC-IIC2223/syllabus#15]
Hola!

Del enunciado entiendo que para que la palabra _w_ pertenezca a _L_n_ la cantidad de letras _a_ agrupadas ( _a^i_ ) tiene que ser menor a _n_, sin embargo no me queda claro si la cantidad de _#a^i_ que aparezcan en la palabra w esta restringido por _n_ o no.

Usando el mismo ejemplo de enunciado, #a#a#a entiendo que pertenece a _L_3_ 
 ¿Pero _#a#a#a#a#a#a_ pertenecería a _L_3_?

Saludos :)

**Comment by Drpinto1** [comment]
¡Hola!

Ya se hizo una pregunta muy parecida en la issue #10, avísame si responde tu duda o si apuntaba a otra cosa.

¡Saludos! :full_moon_with_face:

**Comment by CristobalHV** [comment]
> ¡Hola!
> 
> Ya se hizo una pregunta muy parecida en la issue #10, avísame si responde tu duda o si apuntaba a otra cosa.
> 
> ¡Saludos! 🌝

Es parecida pero no apunta a lo mismo. Entiendo que pregunta si se puede repetir el _i_ en los _a^i_, es decir, que hayan agrupaciones de _a_ con la misma cantidad de _a_

Mi pregunta va a si la cantidad de _#a^i_ que pueden aparecer en la palabra está restringida por _n_ 

Por ejemplo, para un alfabeto _L_3_, la palabra #a#a#a#a repite cuatro veces _#a^i_, pertenecería a _L_3_?

**Comment by fgbruna** [comment]
@CristobalHV fíjate bien que eso es lo primero que responde Dante en la issue que referencia!
