### ISSUE TITLE
[T1.P2] Definir NFA a partir del DFA construido antes

### ISSUE THREAD

**Issue by fprebolledo** [PUC-IIC2223/syllabus#16]
Hola! para la parte 1 construí el NFA a partir del DFA que la 1.1. Mi pregunta es para definir Delta del NFA puedo utilizar la función del DFA anterior? algo como delta = (p, a, q)  talque esté en el dfa y cumpla con tal otra cosa?

**Comment by ricardor4** [comment]
En la definición de la relación de transición del NFA  puedes hacer referencia a la función de transición del DFA
