### ISSUE TITLE
[T1.P1] Definición de autómata

### ISSUE THREAD

**Issue by SarahEverke** [PUC-IIC2223/syllabus#17]
Hola, 
en la 1 hay que definir el autómata como A=(Q, Sigma, d, q0,F) o puede ser la ilustración?

**Comment by Drpinto1** [comment]
¡Hola!

La idea es que puedan definir formalmente el autómata para no quede ambigüedad en su composición, sin embargo una imagen que lo represente es buena y totalmente recomendada, pues nos ayudará a entender la idea detrás y facilitará la explicación que se pide en la pregunta.

¡Saludos!
