### ISSUE TITLE
[Clases] q_0 en Subset Construction

### ISSUE THREAD

**Issue by asimonv** [PUC-IIC2223/syllabus#19]
![image](https://user-images.githubusercontent.com/7036160/91328488-051ab080-e795-11ea-9409-8b5d195e7e68.png)

Profesor, ayudantes, me queda una duda con respecto a como elegir un estado inicial para pasar de NFA a DFA, en las diapositivas dice que q_0^{det} = I, siendo que I es un conjunto. Es un typo y deberia ser un pertenece en vez de una igualdad? En ese caso, se elige un q_0 cualquiera de I para la construcción del DFA?

**Comment by Drpinto1** [comment]
¡Hola @asimonv!

La forma en que está escrito el estado inicial está correcta, pues si miras la definición del conunto de estados del autómata determinizado, podrás notar que **cada estado** de este autómata **será un subconjunto de estados del autómata original** y, en particular, el estado inicial será el conjunto de estados iniciales.

Esta idea puede ser contraintuitiva al inicio, sin embargo si miras el ejemplo de la slide anterior a la que mandas podrás ver a qué nos referimos con que cada estado es un conjunto. 

¡Saludos!

**Comment by asimonv** [comment]
Sí, muchas gracias @Drpinto1!
