### ISSUE TITLE
Tarea 1, pregunta 1: Las palabras pueden terminar en #?

### ISSUE THREAD

**Issue by MrEarle** [PUC-IIC2223/syllabus#2]
Según la definicion en el enunciado, puede una palabra terminar en #?

De acuerdo a como se definen las palabras en ![ln](http://www.sciweavers.org/tex2img.php?eq=L_n&bc=White&fc=Black&im=jpg&fs=12&ff=arev&edit=0) me da la impresión de que una palabra como `#aaa#` es parte de ![ln](http://www.sciweavers.org/tex2img.php?eq=L_n&bc=White&fc=Black&im=jpg&fs=12&ff=arev&edit=0) (este sería un caso con ![ln](http://www.sciweavers.org/tex2img.php?eq=i%3D1&bc=White&fc=Black&im=jpg&fs=12&ff=arev&edit=0))

**Comment by Drpinto1** [comment]
¡Hola @MrEarle!

La respuesta corta es que no, las palabras del lenguaje no pueden terminar en `#`.


La respuesta ligeramente más larga, y la razón detrás de esto, es la parte de la definición del lenguaje que nos indica que estará formado por las palabras de la forma:

![image](https://user-images.githubusercontent.com/26233548/90940605-5a457380-e3dd-11ea-800d-435cf641bea0.png)

Con
![image](https://user-images.githubusercontent.com/26233548/90940739-d63fbb80-e3dd-11ea-8590-cea98611b56a.png)

Pues esto significa que luego de cada símbolo `#` debe venir **al menos una** letra `a`

Avísame si con esto se resuelve tu duda :smile:

**Comment by MrEarle** [comment]
Eso pensaba, gracias!
