### ISSUE TITLE
[T1]Utilización de \vdash^* en la tarea

### ISSUE THREAD

**Issue by JJJGGGG** [PUC-IIC2223/syllabus#20]
Hola! Quería saber si podíamos usar el operador \vdash^* (⊢^* ) en la tarea para simplificar las runs, o el operador \delta^* con el mismo efecto.

**Comment by crivero1** [comment]
Hola @JJJGGGG,

Si lo defines puedes ocuparlo. Pueden ocupar todo hasta las clases de la semana pasada. Si quieres usar algo de la clase de esta semana, tienes que definirlo y, si usas un resultado, demostrarlo. 

Saludos,

Cristian
