### ISSUE TITLE
[T2.P1.2] Como analizar las palabras del lenguaje

### ISSUE THREAD

**Issue by KnowYourselves** [PUC-IIC2223/syllabus#21]
Hola!

Respecto a esta pregunta tengo una duda. Tenemos que este lenguaje acepta tuplas, por ejemplo `(0, 1)(1, 0)`, pero para efectos de la RegEx, ¿Debemos conisderar los paréntesis, o lo podemos ver como una palabra "continua", por ej `"0110"`?. 

Muchas gracias!

**Comment by cahinostroza** [comment]
Hola @KnowYourselves , para efectos de la RegEx deben considerar los paréntesis y las comas también, ya que la palabra "continua" no pertenece al lenguaje dado.

**Comment by KnowYourselves** [comment]
Muchas gracias @cahinostroza!

¿Para diferenciar entres los paréntesis de operadores y los paréntesis del RegEx debemos utilizar alguna nomenclatura especial?, Por ejemplo `(\(0,1\))*`.

**Comment by cahinostroza** [comment]
@KnowYourselves , puedes utilizar la nomenclatura que desees, siempre y cuando la expliques antes, en lo personal, ocuparía comillas para diferenciar a los paréntesis que son caracteres ('('0,1')')*

**Comment by KnowYourselves** [comment]
Yap, haré eso entonces. Gracias!

**Comment by jgespinosa10** [comment]
Hola, para esta pregunta, ¿solo considero los que son 2 tuplas consecutivas? ¿o puede ser de cualquier largo?
Por ejemplo, ¿(1,0)(0,0)(0,1) pertenece a L?

**Comment by Drpinto1** [comment]
¡Hola @jgespinosa10!

Se respondió algo así en la issue #22 

¡Saludos!

**Comment by JJJGGGG** [comment]
Hola! Aún me surge una duda respecto de la pregunta. 

![image](https://user-images.githubusercontent.com/48324565/91788430-2d157400-ebda-11ea-9f2b-89124d780e4c.png)
Aquí dice que Sigma_2 = {0,1}x{0,1} y que estamos considerando palabras w en Sigma_2*, es decir, cualquier combinación de las "letras" de Sigma_2. Al hacer {0,1}x{0,1} entonces se refiere a las tuplas (a,b) y consideramos estas tuplas como "letras" de nuestro alfabeto? Gracias!

**Comment by Drpinto1** [comment]
¡Hola @JJJGGGG!

Exactamente esa es la idea, para expresiones regulares tu alfabeto puede ser lo que sea y en particular en este caso serán esas tuplas.

¡Saludos!

**Comment by JJJGGGG** [comment]
Gracias! En ese caso, podemos usar transiciones delta del estilo \delta('p_0, ('0,1')') = p_1 ?

**Comment by fgbruna** [comment]
@JJJGGGG por supuesto, eso es lo que deberían hacer ya que las transiciones de un autómata(un DFA por ejemplo) se ven de la forma ![\delta(q \in Q, c \in \Sigma) = p \in Q
](https://render.githubusercontent.com/render/math?math=%5Cdisplaystyle+%5Cdelta%28q+%5Cin+Q%2C+c+%5Cin+%5CSigma%29+%3D+p+%5Cin+Q%0A) y la única gracia es que aquí tus "letras" c son tuplas.
Saludos!
