### ISSUE TITLE
[T2.P1.2] Tuplas de largo impar

### ISSUE THREAD

**Issue by KnowYourselves** [PUC-IIC2223/syllabus#22]
Hola!

¿El lenguaje definido acepta tuplas de largo impar?, Por ejemplo:

1. `(0,0)`
2. `(0,0)(0,1)(1,0)`

Gracias!

**Comment by cahinostroza** [comment]
Hola @KnowYourselves , por su puesto, mientras se cumpla lo descrito en el enunciado: "para todo par
consecutivo (a, b) y (c, d) se tiene que b = c". Ambos casos que pusiste pertenecerían al lenguaje.

**Comment by KnowYourselves** [comment]
Perfect! Muchas gracias!
