### ISSUE TITLE
[T2.P2] v_k y u_k pueden ser vacio?

### ISSUE THREAD

**Issue by Okhan97** [PUC-IIC2223/syllabus#23]
Hola,

Según la definición de la tarea tanto v_k como u_k pertenecen a Sigma estrella, esto significa que pueden ser epsilon (vacío)?
Pregunto particularmente para este caso:
R1 = {ad}
R2 = {bb,cc}

Claramente palabras que pertenecen a R1↓↓R2:
adbb, adcc, abdb, acdc
debido a las siguientes divisiones (paréntesis para R1 y corchetes para R2):
(ad)[bb]
(ad)[cc]
(a) [b] (d) [b]
(a) [c] (d)[c]

Sin embargo podríamos también agregar:
abbd, accd
Si es que las consideramos de la forma:
(a) [bb] (d)[]
(a) [cc] (d)[] 

Aún mas, podríamos agregar:
bbad, cacd
Con esta forma:
() [bb] (ad) []
() [c] (a) [c] (d) []

Según entiendo por enunciado esto si se puede pero pregunto para confirmar.

**Comment by cahinostroza** [comment]
Hola @Okhan97 , efectivamente cualquiera de los dos puede ser epsilon. Saludos!

**Comment by VicenteVicente** [comment]
Entonces podría estar épsilon en L2?

**Comment by cahinostroza** [comment]
Hola @VicenteVicente, depende exclusivamente de las expresiones regulares que tomes ya que si alguno de los lenguajes definidos por las expresiones regulares no contiene el epsilon, no puedes generarlo, por la definición del operador. Asumiendo que con L2 te refieres al lenguaje generado por el operador entre R1 y R2. Saludos.
