### ISSUE TITLE
[T2.P1] Formalidad de la respuesta

### ISSUE THREAD

**Issue by KnowYourselves** [PUC-IIC2223/syllabus#24]
Hola!

Mis disculpas por hacer de nuevo exactamente la misma pregunta. ¿Para nuestras RegEx, basta explicar paso por paso por qué creemos que hacen lo pedido, o debemos demostrarlo?

Gracias!

**Comment by cahinostroza** [comment]
Hola @KnowYourselves , no es necesario que hagan una demostración, basta que expliquen, como dice el enunciado "Explique su respuesta". Saludos!

**Comment by DiegoEmilio01** [comment]
Si usamos un automata para ilustrar una idea, ¿debemos definirlo formalmente o podemos solamente mostrar el diagrama de estados?

**Comment by cahinostroza** [comment]
Hola @DiegoEmilio01 , ya que no es una demostración formal, no es necesario que definas el autómata formalmente. Pero trata que tu diagrama sea lo suficientemente claro y explicativo. Saludos.
