### ISSUE TITLE
[T2.P1.1] Duda respecto al lenguaje

### ISSUE THREAD

**Issue by KnowYourselves** [PUC-IIC2223/syllabus#25]
Hola!

En parte de la descripción de esta pregunta sale este lenguaje:

![image](https://user-images.githubusercontent.com/26102039/91628847-b4bc7200-e991-11ea-9d5e-10f3b31f4506.png)

¿El `01+` es `0` seguido de uno o más `1`, o uno o más `01`? 

Gracias!

**Comment by cahinostroza** [comment]
Hola @KnowYourselves , el ```01+``` es ```0``` seguido de uno o más ```1```, uno o más ```01```, hubiese sido ```(01)+```, saludos.
