### ISSUE TITLE
Materia disponible para utilizar en la tarea

### ISSUE THREAD

**Issue by JJJGGGG** [PUC-IIC2223/syllabus#27]
Hola! Me surgió la duda, ya que para la tarea anterior teníamos restricciones en este ámbito. Podemos usar el teorema de Kleene y los algoritmos descritos hasta el lunes 31/08?

**Comment by cahinostroza** [comment]
Hola @JJJGGGG, para las tareas puedes ocupar el material hasta el día antes en que se publique la tarea, si quieres utilizar algún resultado que se vea después, debes demostrarlo. Saludos.
