### ISSUE TITLE
[T2 P1.2] Palabra vacía

### ISSUE THREAD

**Issue by VicenteMerino** [PUC-IIC2223/syllabus#28]
Hola, el lenguaje de la pregunta 1.2 puede aceptar el vacío? Mi intuición es que si, ya que es el lenguaje de todas las palabras w ∈ Σ2∗ tal que para todo par consecutivo (a, b) y (c, d) se tiene que b = c y si no hay ningún par (palabra vacía) entonces se sigue cumpliendo la condición.

**Comment by cahinostroza** [comment]
Hola @VicenteMerino, efectivamente el lenguaje acepta el vacío. Saludos
