### ISSUE TITLE
[T2.P2] ¿Qué cosas podemos asumir?

### ISSUE THREAD

**Issue by jvlara** [PUC-IIC2223/syllabus#29]
Hola,
Al momento de realizar esta pregunta me resulto la duda de si podemos asumir que toda expresion regular tiene un automata que la define y por lo tanto, un lenguaje regular por teorema, ya que al mostrar que existe una expresion regular R3 la cual cumple con el operador del enunciado no se que camino seguir para demostrar que define un lenguaje regular.

**Comment by fgbruna** [comment]
Hola @jvlara, ustedes efectivamente pueden hacer uso del Teorema de Kleene en la P2,
Saludos!
