### ISSUE TITLE
[T1.P1] Valores posibles de n

### ISSUE THREAD

**Issue by VicenteMerino** [PUC-IIC2223/syllabus#3]
Cuando dicen "Para un n arbitrario muestre..." se refiere para un n>=2 verdad? porque no se define el lenguaje Ln para n<2 por definición, entonces no tendría mucho sentido la pregunta.

**Comment by Drpinto1** [comment]
¡Hola @VicenteMerino!

Efectivamente hace referencia a un `n>=2` pues para ese valor está definido el lenguaje 😄

La idea de referirse a un "n arbitrario" es explicitar que su construcción debe servir para cualquier `n` para el que esté definido el lenguaje, por lo que no basta con que definan el autómata para un caso particular.
