### ISSUE TITLE
[Control 1] Aclaración sobre firma en entrega

### ISSUE THREAD

**Issue by JJJGGGG** [PUC-IIC2223/syllabus#30]
Hola! En el anuncio de canvas, el profesor anunció que no recibirá pruebas que no estén firmadas. Con esto, se refiere con escribir nuestro nombre completo o es necesario escanear nuestra firma real?

Gracias

**Comment by nicovsj** [comment]
Hola @JJJGGGG, 

En general, si vas a escanear tus respuestas pedimos que coloques tu firma real. Si justo ocurre que tu firma es tu nombre entonces debes colocarlo de manera explícita después de la frase del código de honor que les pedimos (tal y como estuvieses firmando de verdad). 

Dicho eso, si quieres utilizar LaTeX o similares para la entrega de tus respuestas y te complica mucho colocar tu firma digital, aceptaremos que coloques tu nombre solamente (también junto a la frase del código de honor). 

Saludos!
