### ISSUE TITLE
Comentarios T1P1

### ISSUE THREAD

**Issue by Jamidd** [PUC-IIC2223/syllabus#31]
Hola, quería saber si no subieron el comentario de la pregunta 1 o simplemente no tengo. La pregunta 2 la tengo "súper rallada" pero nada en la 1. 

Gracias. 
Jaime

**Comment by nicovsj** [comment]
Hola Jaime, 

Revisando tu caso, me parece que es porque tuviste todo bueno en esa pregunta y el ayudante decidió no colocar nada. 

Para evitar confusiones acabo de subir las notas de cada pregunta de la tarea a Siding.

Saludos!
