### ISSUE TITLE
Sistema de puntuación

### ISSUE THREAD

**Issue by VicenteMerino** [PUC-IIC2223/syllabus#4]
Hola el enunciado dice

> La evaluación de cada pregunta en una tarea se
evaluará con un puntaje de:
>- 0 (respuesta incorrecta),
>- 3 (con errores menores),
>- 4 (correcta).

Recuerdo que cuando di discreta si la P1 tenía parte a y b, entonces se evaluaba con ese criterio para parte a y la parte b. No se si eso se mantiene en este curso? O el sistema corre para la pregunta "como un todo"?

Gracias

**Comment by nicovsj** [comment]
Hola Vicente, 

Efectivamente la asignación de puntajes es como en Matemáticas Discretas (curso que @crivero1 también dicta). Es decir, si una pregunta tiene 2 ítems, luego en cada ítem puedes tener 0, 3 o 4 puntos dependiendo de que tan buena está tu respuesta, de manera que el puntaje total de esa pregunta será 8. 

También aprovecho de aclarar que la nota de cada tarea se calcula como el promedio entre las notas de cada pregunta.

Saludos!
