### ISSUE TITLE
[Control 2]

### ISSUE THREAD

**Issue by bgsamilla** [PUC-IIC2223/syllabus#48]
Hola!

Se que se respondian dudas en el horario de clases pero no pude partir el control en ese horario.

Ojala me puedan responder ...

En la pregunta 2
Se define el lenguaje de acuerdo a una variable X. L(X) = { ..... }
Sin embargo en el resto de la pregunta se habla de L(G) donde G es una gramatica.

No encontre algo al respecto en el drive.

Me pueden explicar a que se refiere esto?

**Comment by bgsamilla** [comment]
Agradeceria tambien en el caso de que no me puedan responder que me lo hagan saber para no estar esperando una respuesta.
Gracias!

**Comment by crivero1** [comment]
Hola Barbara, 

Acabo de ver tu mensaje, por eso no lo pude responder antes. 

Lamentablemente no podemos responder ninguna pregunta del enunciado o contenido de la materia fuera del horario oficial del control. La razón no es por "mala onda", si no para ser justo con todos los estudiantes por igual. En los controles presenciales nunca respondo preguntas personales y siempre todas las preguntas y respuestas son a viva voz, para que todos tengan la misma información del enunciado. En este caso (controles online), tratamos de hacer lo mismo y por eso las preguntas se responden solo en el horario oficial. Si respondemos preguntas después del horario oficial, esto sería injusto con los estudiantes que ya entregaron el control. 

Espero que entiendas los motivos y perdona la demora. 

Saludos!
