### ISSUE TITLE
[T1.P1] Formalidad de la explicación

### ISSUE THREAD

**Issue by KnowYourselves** [PUC-IIC2223/syllabus#5]
Hola!

Respecto a esta pregunta, en sus dos apartados tenemos que explicar porque los automatas construidos son correctos, ¿Esta explicación debe ser una demostración formal (por contradicción, inducción, etc) o basta con que sea una explicación paso por paso?

Muchas Gracias!

**Comment by Drpinto1** [comment]
¡Hola @KnowYourselves!

No es necesario que hagan una demostración formal, la idea de esa pregunta es que hagan una explicación de su construcción y de por qué debería aceptar el lenguaje, puede ser paso por paso, puede ser explicando los estado y transiciones o puede ser lo que se les ocurra mientras aclare qué está haciendo el autómata al aceptar (o no) una palabra.

¡Saludos!

**Comment by smrebolledo** [comment]
Con construccion se refiere a definir cada uno de los elementos de A=(Q, Sigma, d, q0,F) o al diagrama con estados?

**Comment by Drpinto1** [comment]
¡Hola @smrebolledo!

Disculpa la demora, se me pasó el comentario, pero respondí algo muy parecido en la issue #17 .

Avísame si responde tu duda 😁
