### ISSUE TITLE
[T1.P1] Lenguaje y la palabra vacía

### ISSUE THREAD

**Issue by KnowYourselves** [PUC-IIC2223/syllabus#6]
Hola!

En la pregunta 1, ¿La palabra vacía se puede considerar como parte del lenguaje?

Gracias!

**Comment by Drpinto1** [comment]
¡Hola @KnowYourselves!


La palabra vacía **no** pertenece al lenguaje.

El motivo detrás de esto es que las palabras del lenguaje tienen la forma:

![image](https://user-images.githubusercontent.com/26233548/90940605-5a457380-e3dd-11ea-800d-435cf641bea0.png)

Con `k>0` y con `i>0`. Lo anterior significará que debe existir al menos un grupo de letras `a` (luego de un `#`) y que este grupo debe tener al menos una `a`.


¡Saludos y éxito con la tarea!

**Comment by DiegoEmilio01** [comment]
¿Es posible o debemos argumentar que no se puede? Dadas las restricciones necesitamos una transición para el ```#``` y al menos n para las ```n``` letras ```a```. Entonces son al menos ```n+1``` transiciones para verificar el trozo mas grande posible. Y esos son ```n+2``` estados.

**Comment by Drpinto1** [comment]
Hola @DiegoEmilio01,

Creo que este comentario era para la issue #13, porque no estoy seguro de cómo se relaciona con esta discusión.

De todas maneras, si no es este el caso, puedes complementar un poco más tu comentario para poder responderte.

¡Saludos! :new_moon_with_face:

**Comment by DiegoEmilio01** [comment]
A sí, no se nota tanto. Pero solo he podido hacerlo aceptando la palabra vacía, por eso preguntaba.

**Comment by crivero1** [comment]
Hola Diego,

Tienes razón, tiene un error el enunciado. Acabo de actualizar y avisar sobre este error. Específicamente, \epsilon tiene que estar en Ln o si no la pregunta 1.2 no se puede resolver. 

Saludos!

**Comment by DiegoEmilio01** [comment]
Muchas gracias profesor. Perdón a todos por la hora
