### ISSUE TITLE
[T1] Límite de hojas por pregunta

### ISSUE THREAD

**Issue by VicenteMerino** [PUC-IIC2223/syllabus#7]
Hola, cuál es el límite de hojas por pregunta? O no es relevante en la medida que no abusemos del espacio?

**Comment by Drpinto1** [comment]
¡Hola @VicenteMerino!

No hay un límite definido de hojas por pregunta, por lo que si desean incluir figuras o tablas que aportan a la solución pueden hacerlo sin preocuparse por usar muchas hojas/espacio (sobre todo ahora que la entrega es online).

Dicho esto, si sientes que estás utilizando muchas hojas para una sola pregunta intenta cuestionarte qué partes de tu respuesta son esenciales y qué partes está siendo redundantes y con esto quizás puedas reducir un poco este número.

¡Saludos!
