### ISSUE TITLE
[T1.P2] Podemos usar transiciones epsilon?

### ISSUE THREAD

**Issue by MrEarle** [PUC-IIC2223/syllabus#8]
En la pregunta 2.1, podemos usar transiciones epsilon para construir el NFA?

**Comment by crivero1** [comment]
Hola, 

No hemos visto transiciones epsilon, así que no, no pueden usarlo aún en esa pregunta. 

Saludos!

**Comment by fprebolledo** [comment]
Creo que sin estas no se puede resolver la pregunta 2.1.
Para el siguiente ejemplo de DFA visto en clases, como se acepta la palabra epsilon, el estado inicial debe ser un estado final, ahora si queremos aceptar una a, si o si debemos devolvernos al estado inicial  lo cual termina aceptando cualquiera palabra del tipo i veces a y lo que hacía este autómata es rechazar los pares de a seguidas.

![imagen](https://user-images.githubusercontent.com/26394880/91111001-59b31400-e64d-11ea-8de3-36f07fed5b3d.png)

**Comment by crivero1** [comment]
Hola Francisca,

Si, tienes toda la razón. Acabo de actualizar el enunciado y dar un aviso sobre este error. Muchas gracias por avisarnos. 

Saludos!
