### ISSUE TITLE
[Clases] NFAp

### ISSUE THREAD

**Issue by VicenteMerino** [PUC-IIC2223/syllabus#9]
Hola, en un NFA necesariamente deben estar todas las transiciones? Por ejemplo si tengo un alfabeto {0,1} y estoy en un estado A, puede pasar que solo tenga transición para el 0? Algo similar a las funciones parciales de transición

**Comment by Drpinto1** [comment]
¡Hola!

En un NFA no es necesario que todos los estados tengan transiciones para todos los símbolos del alfabeto. Si miramos, por ejemplo, el primer NFA que vieron en clases:

![image](https://user-images.githubusercontent.com/26233548/90966770-9db6e500-e4a4-11ea-846e-d195329d3562.png)

Podemos ver que el estado `1` solamente tiene transiciones para la letra `b`, pero no para la `a`. Esto es posible porque, en lugar de la **función de transición** de los DFA, tenemos una **relación de transición**, que corresponde a un concepto mucho menos restrictivo y, como mencionas, se comportará de forma similar a los DFAp que vieron antes.

¡Saludos!
